### ISSUE TITLE
[Bug]: SyntaxError on Startup and reset settings of Commander including all buttons

### ISSUE THREAD

**Issue by MasterRedStorm** [phibr0/obsidian-commander#131]
### Describe the bug

Having a new Vault and only Commander installed, sometimes on startup i get this:
![grafik](https://github.com/phibr0/obsidian-commander/assets/23191670/ab70d06e-a956-48f0-adf2-5334d4f109ef)

After that, the buttons i added via commander are missing.

Iam using Obsidian v.1.5.12

### Relevant errors (if available)

```Shell
app.js:1 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at t.<anonymous> (app.js:1:732057)
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)
```

### Steps to reproduce

Create a new Vault and add the community plugin Commander.
Then restart obsidian 1 to 2 times and see the error :)

### Operating system

Windows

**Comment by jsmorabito** [comment]
hi @MasterRedStorm I put out a new release please see if this is resolved for you
